# Generated by Django 2.2.5 on 2020-06-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20200618_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='learn_times',
        ),
        migrations.AddField(
            model_name='video',
            name='video_times',
            field=models.FloatField(default=0, verbose_name='视频时长(分钟数)'),
        ),
    ]
